artifacts_root: artifacts

data_ingestion:
      root_dir: data_ingestion
      source_URL: https://github.com/basajjabaka/textSummarizer/raw/refs/heads/main/summarizer-data.zip
      local_data_file: artifacts/data_ingestion/data.zip
      unzip_dir: artifacts/data_ingestion


data_validation:
      root_dir: data_validation
      STATUS_FILE: artifacts/data_validation/status.txt
      RQD_FILE: ['train', 'test', 'validation']